// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
//
// The Supabase client is imported lazily rather than at module scope. This
// middleware is registered globally, so a static import pulled the whole
// @supabase/supabase-js SDK (~150kB min) into the client entry chunk on every
// page, even though it is only needed once a serverFn RPC actually fires.
// Deferring it keeps the SDK in its own async chunk that is fetched on first
// use. Behaviour is unchanged.
export const attachSupabaseAuth = createMiddleware({ type: "function" }).client(
  async ({ next }) => {
    const { supabase } = await import("./client");
    const { data } = await supabase.auth.getSession();
    const token = data.session?.access_token;
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
  },
);
